version: "3.9"
services:
  general_server:
    build: ./HOI-GeneralServer
    ports: 
      - "50888:50888"
    env_file: .env
  external_controller:
    build: ./ExternalController
    env_file: .env
    ports:
      - "50889:50889"